permissions:
  repository-projects: read

name: Notify Discord on Status Change
on:
  project_item:
    types: [edited]

jobs:
  check_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          # GitHub sender data om hvad der blev ændret i 'github.event'
          PROJECT_DATA: ${{ toJson(github.event) }}
        run: python notify_status.py